### ISSUE TITLE
I dont know why no one has reported this yet

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [V0idWa1k3r/Aetherworks#5]
Embers Transfered owners after Elucent left. Then Bord started work on Embers Rekindled (github only for now) and the main embers repo being worked on by EpicSquid will become Embers 2. Your project will probally fall under Embers Rekindled. That release is listed here https://github.com/EpicSquid/Embers/releases and claims to have issues with this mod. Embers Rekindled will be moved to curseforge and the main Embers repo will become the new Embers 2 Repo. When Embers Rekindled is moved make sure to support it because it will become Embers 1 (Embers Classic). That also means you should try to fix the API, that EpicSquid said was broken

**Comment by DaedalusGame** [comment]
probably because i made sure to keep binary compatibility for addons to the best of my ability and there's atleast one guy that told me that aetherworks works fine with Rekindled. Although I haven't done indepth testing.

**Comment by wamc2017** [comment]
I tested aetherworks with rekindled and had no issues with the latest test build (which is over a month old, so can't say if it works with the latest changes)

**Comment by Dragnier** [comment]
I tried swapping to Rekindleated from regular today and got a crash during load before the main menu. https://paste.dimdev.org/kolalucera.mccrash

Edit: This now looks like an error on their side. Time to go over there...
