### ISSUE TITLE
[1.12.2] [1.0.0.3] Incompatibility with Embers Rekindled 1.6+

### ISSUE THREAD

**Issue by wamc2017** [V0idWa1k3r/Aetherworks#6]
Hi,

Embers Rekindled changed gases to be voided in reservoirs and vessels in [1.6](https://minecraft.curseforge.com/projects/embers-rekindled/files/2610520), as you can assume this break the aether collector.

Thanks for looking into it.

Best regards,
wamc

**Comment by DaedalusGame** [comment]
talk about hidden consequences

**Comment by DaedalusGame** [comment]
I've changed the behavior of reservoirs and vessels to only void if the density is negative. This won't fix anything ad-hoc but you can mark aetherium gas density positive now to fix this. Sorry for the hassle, it was intended to be a small change to prevent people from stashing tons of steam in large tanks.

**Comment by V0idWa1k3r** [comment]
See [MinecraftForge#3746](https://github.com/MinecraftForge/MinecraftForge/issues/3746)(closed because of stale, not because it was resolved). A gaseous fluid with a positive density will have trouble rendering. I'll just make aetherium a regular fluid I guess.

**Comment by wamc2017** [comment]
Any new on this?

**Comment by V0idWa1k3r** [comment]
Kinda busy with IRL stuff right now, will get back to things in maybe a week or so. Sorry for the delays.

**Comment by wamc2017** [comment]
This was fixed on embers side (https://github.com/DaedalusGame/EmbersRekindled/commit/e203bb858fc73b7343e357e5dd5413381f3df4b2)
